### ISSUE TITLE
Add vim and tcl syntax to base image

### ISSUE THREAD

**Issue by ismell** [eggheads/eggdrop-docker#6]
It would be nice to have a full vim version in the docker base image. This way I can login to the container and edit config or tcl files.

    docker exec -it my-eggdrop /bin/bash

I rum my container with a volume container so it's not available from the host box.

**Comment by realies** [comment]
It's better to have your configuration and TCL files in a persistent storage exposed to the container. No need to bloat the image.

**Comment by vanosg** [comment]
Somehow I missed you filing this issue, my apologies. Generally yes, we don't want to install anything extra inside the image, and will probably continue to cut down on non-essential code as much as possible. 

BUT the good news is, you can still edit a volume container directly from the host! run ```docker inspect -f "{{json .Mounts}}" yourEggdropContainerName``` and look at the "Source" field- that will list where your data volume is stored on the host OS. And because data volumes exist outside the Union filesystem, you can edit it from the host and not worry about some of the corruption issues you encounter editing the container filesystem directly. I hope this helps

**Comment by vanosg** [comment]
Fun fact, however... it looks like alpine includes a stripped down version of vi in its core OS, so that option is already present! You learn something new every day
